name: Build DevilutionX PSP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout build repo
        uses: actions/checkout@v4

      - name: Setup PSP toolchain
        uses: krystalgamer/setup-psptoolchain@latest

      - name: Build DevilutionX PSP
        run: bash build-psp.sh

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: DevilutionX-PSP
          path: package/
          if-no-files-found: error
